// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace personaldetails.Migrations.Team
{
    [DbContext(typeof(TeamContext))]
    partial class TeamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("personaldetails.Models.Team", b =>
                {
                    b.Property<int>("empid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("empid"));

                    b.Property<string>("empemail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("team_lead")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("team_manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("team_mem1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("team_mem2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("team_mem3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("team_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("empid");

                    b.ToTable("Teamdet");
                });
#pragma warning restore 612, 618
        }
    }
}
